apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: k3s-home

resources:
  - deployment.yaml
  - service.yaml


# configMapGenerator:
#   - name: nginx-html
#     files:
#     - html/index.html